# Generated by Django 2.0.10 on 2019-02-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binatang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='binatang',
            name='images',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
